spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        show_sql: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

logging:
  level:
    root: WARN
    org:
      SQL: DEBUG
      hibernate:
        orm.jdbc.bind: TRACE
        type.descriptor.sql.BasicBinder: TRACE
      springframework:
        web: DEBUG
        transaction: DEBUG
        security: DEBUG
        jdbc.core.JdbcTemplate: DEBUG
app:
  jwt:
    cookie:
      name: Authorization
      domain: unicat.day
      path: /
      secure: true
      httpOnly: true
      sameSite: Lax
      maxAge: 604800

    private-key: ${APP_JWT_PRIVATE_KEY:classpath:keys/private_key.sample}
    public-key: ${APP_JWT_PUBLIC_KEY:classpath:keys/public_key.sample}
    key-id: ${APP_JWT_KEY_ID:rsa-key-id}

server:
  ssl:
    key-store: ${APP_SSL_KEY_STORE:classpath:keys/unicat.p12}
    key-store-type: ${APP_SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${APP_SSL_KEY_STORE_PASSWORD:unicat123}
    key-alias: ${APP_SSL_KEY_ALIAS:unicat-day}
