spring:
  application:
    name: unicat-api
  config:
    import: classpath:core/application-oauth.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    locale: ko
    locale-resolver: accept-header
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    path: /

app:
  name: unicat-api
  jwt:
    private-key: ${APP_JWT_PRIVATE_KEY}
    public-key: ${APP_JWT_PUBLIC_KEY}
    key-id: ${APP_JWT_KEY_ID}
    cookie:
      name: Authorization
      domain: ${APP_JWT_COOKIE_DOMAIN}
      path: /
      secure: ${APP_JWT_COOKIE_SECURE:true}
      httpOnly: ${APP_JWT_COOKIE_HTTP_ONLY:true}
      sameSite: ${APP_JWT_COOKIE_SAME_SITE:Lax}
      maxAge: ${APP_JWT_COOKIE_MAX_AGE:604800}
  api:
    protocol: https
    domain: api.unicat.day
    port: 443
  toss:
    client-key: ${APP_TOSS_CLIENT_KEY}
    secret-key: ${APP_TOSS_SECRET_KEY}
    confirm-url: ${APP_TOSS_CONFIRM_URL}
    cancel-url: ${APP_TOSS_CANCEL_URL}
  supabase:
    url: ${SUPABASE_URL}
    key: ${SUPABASE_KEY}
    storage:
      bucket: media
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
    allowed-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    allow-credentials: true
    max-age: 3600

server:
  port: 443
  http2:
    enabled: true
  ssl:
    key-store: ${APP_SSL_KEY_STORE}
    key-store-type: ${APP_SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${APP_SSL_KEY_STORE_PASSWORD}
    key-alias: ${APP_SSL_KEY_ALIAS}
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always